// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stzmklayujbxxswpbqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0em1rbGF5dWpieHhzd3BicXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMjQ5OTUsImV4cCI6MjA1NTkwMDk5NX0.T2ifa7_g3A_FAhGX1ujANkmoIG00Cm2_pqKg_GsaqmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);